name: pruple_kookoo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  selection_menu: ^2.0.2
  crypto_font_icons: ^1.0.1
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.1.1+1
  cryptocoins_icons:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Ham.png
    - assets/images/kookoo.png
    - assets/images/Long.svg
    - assets/images/short.svg
    - assets/images/Long.png
    - assets/images/alarm.png
    - assets/images/alarm1.png
    - assets/images/short.png
    - assets/images/bull.png
    - assets/images/bear.png
    - assets/images/usdt.png
    - assets/images/btc.png
    - assets/images/eth.png
    - assets/images/bnb.png
    - assets/images/bcc.png
    - assets/images/neo.png
    - assets/images/ltc.png
    - assets/images/qtum.png
    - assets/images/ada.png
    - assets/images/xrp.png
    - assets/images/eos.png
    - assets/images/tusd.png
    - assets/images/xlm.png
    - assets/images/ont.png
    - assets/images/trx.png
    - assets/images/etc.png
    - assets/images/icx.png
    - assets/images/nuls.png
    - assets/images/vet.png
    - assets/images/pax.png
    - assets/images/usdc.png
    - assets/images/link.png
    - assets/images/waves.png
    - assets/images/btt.png
    - assets/images/ong.png
    - assets/images/hot.png
    - assets/images/zil.png
    - assets/images/zrx.png
    - assets/images/bat.png
    - assets/images/xmr.png
    - assets/images/zec.png
    - assets/images/iost.png
    - assets/images/dash.png
    - assets/images/nano.png
    - assets/images/omg.png
    - assets/images/theta.png
    - assets/images/enj.png
    - assets/images/mith.png
    - assets/images/matic.png
    - assets/images/atom.png
    - assets/images/one.png
    - assets/images/algo.png
    - assets/images/gto.png
    - assets/images/doge.png
    - assets/images/ankr.png
    - assets/images/npxs.png
    - assets/images/mtl.png
    - assets/images/tomo.png
    - assets/images/dent.png
    - assets/images/mft.png
    - assets/images/storm.png
    - assets/images/dock.png
    - assets/images/wan.png
    - assets/images/fun.png
    - assets/images/cvc.png
    - assets/images/band.png
    - assets/images/beam.png
    - assets/images/xtz.png
    - assets/images/ren.png
    - assets/images/rvn.png
    - assets/images/nkn.png
    - assets/images/stx.png
    - assets/images/iotx.png
    - assets/images/rlc.png
    - assets/images/mco.png
    - assets/images/ctxc.png
    - assets/images/bch.png
    - assets/images/rub.png
    - assets/images/eur.png
    - assets/images/bts.png
    - assets/images/lsk.png
    - assets/images/bnt.png
    - assets/images/strat.png
    - assets/images/aion.png
    - assets/images/wtc.png
    - assets/images/data.png
    - assets/images/xzc.png
    - assets/images/sol.png
    - assets/images/btc.png
    - assets/images/btc.png
    - assets/images/gxs.png
    - assets/images/ardr.png
    - assets/images/lend.png
    - assets/images/knc.png
    - assets/images/rep.png
    - assets/images/lrc.png
    - assets/images/comp.png
    - assets/images/sc.png
    - assets/images/zen.png
    - assets/images/snx.png
    - assets/images/eth.png
    - assets/images/eth.png
    - assets/images/ada.png
    - assets/images/ada.png
    - assets/images/link.png
    - assets/images/link.png
    - assets/images/vtho.png
    - assets/images/dgb.png
    - assets/images/gbp.png
    - assets/images/mkr.png
    - assets/images/dai.png
    - assets/images/dcr.png
    - assets/images/storj.png
    - assets/images/bnb.png
    - assets/images/bnb.png
    - assets/images/xtz.png
    - assets/images/xtz.png
    - assets/images/mana.png
    - assets/images/yfi.png
    - assets/images/bal.png
    - assets/images/blz.png
    - assets/images/kmd.png
    - assets/images/dai.png
    - assets/images/ant.png
    - assets/images/crv.png
    - assets/images/sand.png
    - assets/images/nmr.png
    - assets/images/dot.png
    - assets/images/paxg.png
    - assets/images/sushi.png
    - assets/images/ksm.png
    - assets/images/uma.png
    - assets/images/eos.png
    - assets/images/eos.png
    - assets/images/trx.png
    - assets/images/trx.png
    - assets/images/xrp.png
    - assets/images/xrp.png
    - assets/images/dot.png
    - assets/images/dot.png
    - assets/images/ltc.png
    - assets/images/ltc.png
    - assets/images/uni.png
    - assets/images/oxt.png
    - assets/images/uni.png
    - assets/images/uni.png
    - assets/images/utk.png
    - assets/images/aave.png
    - assets/images/fil.png
    - assets/images/fil.png
    - assets/images/fil.png
    - assets/images/yfi.png
    - assets/images/yfi.png
    - assets/images/bch.png
    - assets/images/bch.png
    - assets/images/dnt.png
    - assets/images/xem.png
    - assets/images/aave.png
    - assets/images/aave.png
    - assets/images/skl.png
    - assets/images/sushi.png
    - assets/images/sushi.png
    - assets/images/xlm.png
    - assets/images/xlm.png
    - assets/images/grt.png
    - assets/images/atm.png
    - assets/images/auto.png
    - assets/images/btg.png
    - assets/images/icp.png
    - assets/images/lpt.png
    - assets/images/xvg.png
    - assets/images/mln.png
    - assets/images/req.png
    - assets/images/gno.png
    - assets/images/elf.png
    - assets/images/poly.png
    - assets/images/sys.png
    - assets/images/adx.png
    - assets/images/powr.png
    - assets/images/amp.png
    - assets/images/flux.png
    - assets/images/steem.png
    - assets/images/nexo.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
